updates
Signed-off-by: NilashishC <nilashishchakraborty8@gmail.com>

diff --git a/.github/actions/build-test/action.yml b/.github/actions/build-test/action.yml
--- a/.github/actions/build-test/action.yml
+++ b/.github/actions/build-test/action.yml
@@ -92,10 +92,15 @@ runs:
           --cap-add=SYS_ADMIN --cap-add=SYS_RESOURCE \
           --device /dev/fuse ${{ inputs.namespace }}/${{ inputs.final_image }}:test \
           -c "tests/test.sh"
-          echo "test_rc=$?" >> "$GITHUB_OUTPUT"
+        echo "test_rc=$?" >> "$GITHUB_OUTPUT"
+    
+    - shell: bash
+      run: |
+        x=${{ steps.run-tests.outputs.test_rc }}"
+        echo $x
 
-    # usually, the error rc while propagate back and
-    # the workflow will fail by itself in the previous step
+    # usually, the error rc from within the container will propagate back
+    # and the workflow will fail by itself in the previous step
     # this is kept here just as a fail safe
     - name: Error out if run-tests failed.
       if: ${{ steps.run-tests.outputs.test_rc != 0 }}"
